### ISSUE TITLE
Unicode errors on feed output in Python2

### ISSUE THREAD

**Issue by ckrez** [csirtgadgets/csirtgsdk-py#121]
csirtg --user user --feed ssh-scanning --format table
Traceback (most recent call last):
  File "/usr/local/bin/csirtg", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/csirtgsdk/client/client.py", line 201, in main
    format(data).write()
  File "/usr/local/lib/python2.7/dist-packages/csirtgsdk/format/table.py", line 50, in write
    y = str(y)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd4' in position 5: ordinal not in range(128)

**Comment by ckrez** [comment]
Should be fixed in pull request #122
